const $=s=>document.querySelector(s),form=$('#drawForm'),namesInput=$('#names'),winnerInput=$('#winnerCount'),setup=$('#setup'),factory=$('#factory'),canvas=$('#factoryCanvas'),ctx=canvas.getContext('2d');
const Q=new URLSearchParams(location.search),TEST=Q.has('autotest'),W=900,H=1200,GRAVITY=680,FIXED=1/120,COLORS=['#21d4e2','#ff6b35','#ffd23f','#a78bfa','#3ee09a','#fb7185','#60a5fa','#f59e0b','#2dd4bf','#e879f9'];
let S={running:false,paused:false,sound:true,time:0,last:0,acc:0,balls:[],winners:[],won:[],events:new Set(),particles:[],audio:null,raf:0,seed:1,collisions:0},duplicateConfirmedFor='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),rnd=()=>{S.seed=(S.seed*1664525+1013904223)>>>0;return S.seed/4294967296};
function randomInt(max){if(max<=0)return 0;const limit=0x100000000-(0x100000000%max),a=new Uint32Array(1);let v;do{crypto.getRandomValues(a);v=a[0]}while(v>=limit);return v%max}function shuffle(items){const a=[...items];for(let i=a.length-1;i;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function parsedNames(){return namesInput.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}function updateInput(){const list=parsedNames(),m=new Map();list.forEach(n=>m.set(n,(m.get(n)||0)+1));const d=[...m].filter(([,c])=>c>1).map(([n,c])=>`${n} × ${c}`);$('#participantCount').textContent=list.length;$('#duplicateNotice').hidden=!d.length;$('#duplicateNotice').textContent=d.length?`⚠ 중복 이름이 있어요: ${d.join(', ')} (각각 별도 참가자로 추첨됩니다)`:''}namesInput.addEventListener('input',updateInput);winnerInput.addEventListener('input',()=>$('#error').textContent='');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>winnerInput.value=Math.max(1,(+winnerInput.value||1)+(+b.dataset.step)));
function build(names,count){const people=names.map((name,id)=>({name,id})),winners=shuffle(people).slice(0,count),order=shuffle(winners),r=Math.max(15,23-Math.max(0,names.length-12)*.3),ids=new Set(winners.map(x=>x.id)),rank=new Map(order.map((x,i)=>[x.id,i])),drop=shuffle(people.map(x=>x.id));S.seed=randomInt(0xffffffff)||1;S.winners=order;S.won=[];S.collisions=0;S.particles=[];S.balls=people.map((p,i)=>{const di=drop.indexOf(p.id),port=di%7;return{...p,r,color:COLORS[i%COLORS.length],winner:ids.has(p.id),rank:rank.get(p.id),x:150+port*100+(rnd()-.5)*20,y:58-r*2,vx:(rnd()-.5)*65,vy:0,angle:0,active:false,done:false,launch:.16+di*(names.length>20?.19:.25),trail:[],hits:0}})}
form.addEventListener('submit',e=>{e.preventDefault();const n=parsedNames(),wc=Number(winnerInput.value),err=$('#error');if(!n.length){err.textContent='참여자를 한 명 이상 입력해 주세요.';return}if(!Number.isInteger(wc)||wc<1){err.textContent='당첨자 수를 1명 이상 입력해 주세요.';return}if(wc>n.length){err.textContent=`당첨자 수는 참가자 ${n.length}명보다 많을 수 없습니다.`;return}const sig=n.join('\n');if(new Set(n).size!==n.length&&duplicateConfirmedFor!==sig){if(!confirm('중복된 이름을 각각 별도 참가자로 포함해 추첨할까요?'))return;duplicateConfirmedFor=sig}err.textContent='';initAudio();build(n,wc);setup.hidden=true;factory.hidden=false;start()});
function initAudio(){if(S.audio)return;try{S.audio=new(window.AudioContext||window.webkitAudioContext)()}catch{S.sound=false}}function tone(f=300,d=.04,g=.018,delay=0){if(!S.sound||!S.audio)return;const a=S.audio,o=a.createOscillator(),v=a.createGain();o.type='sine';o.frequency.value=f;v.gain.setValueAtTime(g,a.currentTime+delay);v.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+d);o.connect(v);v.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+d)}function winSound(){[523,659,784,1047].forEach((f,i)=>tone(f,.2,.04,i*.08))}
function start(){S.running=true;S.paused=false;S.time=0;S.acc=0;S.last=performance.now();S.events.clear();$('#liveParticipants').textContent=S.balls.length;$('#winnerProgress').textContent=`0 / ${S.winners.length}`;$('#resultPanel').hidden=true;$('#restartBtn').disabled=true;$('#resetBtn').disabled=true;$('#pauseBtn').disabled=false;$('#pauseBtn').textContent='Ⅱ 일시정지';cancelAnimationFrame(S.raf);if(TEST){runTest(Number(Q.get('stop')||1));return}S.raf=requestAnimationFrame(loop)}
$('#pauseBtn').onclick=()=>{if(!S.running)return;S.paused=!S.paused;$('#pauseBtn').textContent=S.paused?'▶ 재개':'Ⅱ 일시정지';if(!S.paused){S.last=performance.now();S.raf=requestAnimationFrame(loop)}};$('#soundBtn').onclick=()=>{S.sound=!S.sound;$('#soundBtn').textContent=S.sound?'♬ 사운드 ON':'♬ 사운드 OFF';$('#soundBtn').setAttribute('aria-pressed',String(S.sound));if(S.sound){initAudio();tone(520)}};$('#restartBtn').onclick=()=>{build(S.balls.map(b=>b.name),S.winners.length);start()};$('#resetBtn').onclick=()=>{factory.hidden=true;setup.hidden=false;scrollTo({top:0,behavior:'smooth'})};
const EVENTS=[[0,'ZONE 1','DROP','7개 투입구 개방'],[3.2,'ZONE 2','PLINKO','첫 번째 핀 웨이브'],[7,'ZONE 3','CHAOS','범퍼 부스트 ON'],[10.5,'ZONE 3','CHAOS','회전 크로스바 가동'],[13.8,'ZONE 4','BOTTLENECK','이동 바 · 병목 진입'],[17,'FINAL','LAST CHANCE','최종 플리퍼 잠금'],[19,'FINAL','WINNER SLOT','당첨 슬롯 순차 개방']];
function updateEvent(){EVENTS.forEach((e,i)=>{if(S.time>=e[0]&&!S.events.has(i)){S.events.add(i);$('#stageNumber').textContent=e[1];$('#stageTitle').textContent=e[2];$('#statusText').textContent=e[2];$('#phaseText').textContent=e[3];$('#cameraName').textContent=i>4?'FINAL CAM':i>2?'CHAOS CAM':'BOARD CAM';const b=$('#eventBanner');b.querySelector('span').textContent=e[3];b.classList.remove('show');requestAnimationFrame(()=>b.classList.add('show'));setTimeout(()=>b.classList.remove('show'),1500);if(i)tone(210+i*35,.08,.018)}})}
function pins(){const out=[];for(let row=0;row<9;row++){const y=190+row*68,offset=row%2?75:25;for(let x=offset;x<W-30;x+=100)out.push({x,y,r:8,type:'pin'})}return out}const PINS=pins(),BUMPS=[{x:205,y:755,r:40},{x:450,y:700,r:46},{x:695,y:755,r:40}],WALLS=[{x1:45,y1:118,x2:45,y2:1040},{x1:855,y1:118,x2:855,y2:1040},{x1:45,y1:1020,x2:315,y2:1110},{x1:855,y1:1020,x2:585,y2:1110},{x1:315,y1:1110,x2:385,y2:1110},{x1:515,y1:1110,x2:585,y2:1110}];
function loop(now){if(!S.running||S.paused)return;let dt=Math.min(.04,(now-S.last)/1000);S.last=now;S.acc+=dt;while(S.acc>=FIXED){step(FIXED);S.acc-=FIXED}draw();if(S.running)S.raf=requestAnimationFrame(loop)}
function step(dt){S.time+=dt;updateEvent();for(const b of S.balls){if(!b.active&&S.time>=b.launch){b.active=true;b.vy=40}if(!b.active||b.done)continue;b.vy+=GRAVITY*dt;b.vx*=.999;b.vy*=.9995;b.x+=b.vx*dt;b.y+=b.vy*dt;b.angle+=b.vx*dt*.012;collideBounds(b);for(const p of PINS)circleHit(b,p.x,p.y,p.r,.78,0);for(const p of BUMPS)circleHit(b,p.x,p.y,p.r,1.12,300);movingObstacles(b);for(const w of WALLS)segmentHit(b,w,.72);b.trail.push([b.x,b.y]);if(b.trail.length>8)b.trail.shift();if(b.y>910)finalZone(b)}ballCollisions();for(const p of S.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt}S.particles=S.particles.filter(p=>p.life>0);if(S.won.length===S.winners.length&&S.time>21.5)finish()}
function collideBounds(b){if(b.x-b.r<48){b.x=48+b.r;b.vx=Math.abs(b.vx)*.75}if(b.x+b.r>852){b.x=852-b.r;b.vx=-Math.abs(b.vx)*.75}}
function circleHit(b,x,y,r,rest,boost){const dx=b.x-x,dy=b.y-y,d=Math.hypot(dx,dy),min=b.r+r;if(d>=min||!d)return;const nx=dx/d,ny=dy/d,rv=b.vx*nx+b.vy*ny;if(rv<0){b.vx-=(1+rest)*rv*nx;b.vy-=(1+rest)*rv*ny;if(boost){b.vx+=nx*boost;b.vy+=ny*boost;burst(x,y,b.color);tone(360+r*2,.035,.009)}}const push=min-d;b.x+=nx*push;b.y+=ny*push;b.hits++;S.collisions++}
function segmentHit(b,s,rest){const vx=s.x2-s.x1,vy=s.y2-s.y1,l2=vx*vx+vy*vy,t=clamp(((b.x-s.x1)*vx+(b.y-s.y1)*vy)/l2),px=s.x1+t*vx,py=s.y1+t*vy,dx=b.x-px,dy=b.y-py,d=Math.hypot(dx,dy);if(d>=b.r||!d)return;const nx=dx/d,ny=dy/d,rv=b.vx*nx+b.vy*ny;if(rv<0){b.vx-=(1+rest)*rv*nx;b.vy-=(1+rest)*rv*ny}b.x+=nx*(b.r-d);b.y+=ny*(b.r-d)}
function movingObstacles(b){const a=S.time*2.1,cx=450,cy=850,len=135;for(let k=0;k<2;k++){const ang=a+k*Math.PI/2,ex=cx+Math.cos(ang)*len,ey=cy+Math.sin(ang)*len;segmentHit(b,{x1:cx-Math.cos(ang)*len,y1:cy-Math.sin(ang)*len,x2:ex,y2:ey},.92)}const bx=450+Math.sin(S.time*1.8)*210,by=970;segmentHit(b,{x1:bx-105,y1:by,x2:bx+105,y2:by},.82);if(S.time>14){const sy=150+clamp((S.time-14)/4)*820;if(b.y<sy+b.r&&b.y>sy-45){b.y=sy+b.r;b.vy=Math.max(b.vy,410)}}}
function ballCollisions(){const a=S.balls.filter(b=>b.active&&!b.done);for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const x=a[i],y=a[j],dx=y.x-x.x,dy=y.y-x.y,d=Math.hypot(dx,dy),m=x.r+y.r;if(d>=m||!d)continue;const nx=dx/d,ny=dy/d,rv=(y.vx-x.vx)*nx+(y.vy-x.vy)*ny;if(rv<0){const imp=-(1.55)*rv/2;x.vx-=imp*nx;x.vy-=imp*ny;y.vx+=imp*nx;y.vy+=imp*ny}const p=(m-d)/2;x.x-=nx*p;x.y-=ny*p;y.x+=nx*p;y.y+=ny*p;S.collisions++}}
function finalZone(b){const targetTime=18.8+(b.winner?b.rank*.85:0);if(b.y<1050){const funnel=(450-b.x)*1.8;b.vx+=funnel*FIXED;return}if(b.winner){if(S.time<targetTime){b.y=Math.min(b.y,1080);b.vy=-Math.abs(b.vy)*.45;b.vx+=(450-b.x)*5*FIXED;return}b.vx+=(450-b.x)*4*FIXED;if(b.y>1125&&Math.abs(b.x-450)<90){win(b);return}}else{const side=b.id%2?-1:1;b.vx+=side*520*FIXED}if(b.y>1190){b.done=true;b.x=b.id%2?120:780;b.y=1160;b.vx=b.vy=0}}
function win(b){b.done=true;b.x=450;b.y=1160;b.vx=b.vy=0;S.won.push(b);$('#winnerProgress').textContent=`${S.won.length} / ${S.winners.length}`;const t=$('#winnerToast');t.textContent=`★ WINNER ${S.won.length} · ${b.name}`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500);burst(450,1140,'#ffd23f',60);winSound()}
function burst(x,y,color,n=14){for(let i=0;i<n;i++){const a=rnd()*Math.PI*2,s=100+rnd()*330;S.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+rnd()*.7,color})}}
function draw(){ctx.clearRect(0,0,W,H);const zoom=S.time>17?1.08:1,cy=S.time>17?680:600;ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-W/2,-cy);background();board();for(const b of S.balls)if(b.active)drawBall(b);for(const p of S.particles){ctx.globalAlpha=clamp(p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)}ctx.globalAlpha=1;ctx.restore()}
function background(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0d2038');g.addColorStop(.55,'#101a31');g.addColorStop(1,'#190f2b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#1f3550';ctx.lineWidth=1;for(let x=0;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function board(){zone('ZONE 1  DROP',55,95,'#21d4e2');zone('ZONE 2  PLINKO',55,160,'#60a5fa');zone('ZONE 3  CHAOS',55,650,'#ff6b35');zone('ZONE 4  BOTTLENECK',55,945,'#a78bfa');zone('FINAL  WINNER SLOT',560,1145,'#ffd23f');ctx.fillStyle='#86a0bd';for(const p of PINS){ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.fillStyle='#d5e5f7';ctx.beginPath();ctx.arc(p.x-2,p.y-2,2.5,0,7);ctx.fill();ctx.fillStyle='#86a0bd'}for(const p of BUMPS){const pulse=1+Math.sin(S.time*5+p.x)*.07;ctx.save();ctx.translate(p.x,p.y);ctx.scale(pulse,pulse);ctx.fillStyle='#ff6b3533';ctx.strokeStyle='#ff8a58';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.arc(0,0,p.r*.4,0,7);ctx.fill();ctx.restore()}ctx.strokeStyle='#f0a33b';ctx.lineWidth=14;ctx.lineCap='round';const a=S.time*2.1;for(let k=0;k<2;k++){const ang=a+k*Math.PI/2;ctx.beginPath();ctx.moveTo(450-Math.cos(ang)*135,850-Math.sin(ang)*135);ctx.lineTo(450+Math.cos(ang)*135,850+Math.sin(ang)*135);ctx.stroke()}const bx=450+Math.sin(S.time*1.8)*210;ctx.strokeStyle='#a78bfa';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(bx-105,970);ctx.lineTo(bx+105,970);ctx.stroke();if(S.time>14){const sy=150+clamp((S.time-14)/4)*820;ctx.strokeStyle='#21d4e2aa';ctx.lineWidth=7;ctx.setLineDash([18,12]);ctx.beginPath();ctx.moveTo(60,sy);ctx.lineTo(840,sy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#21d4e2';ctx.font='800 11px monospace';ctx.textAlign='center';ctx.fillText('FINAL SWEEP ▼',450,sy-10)}ctx.strokeStyle='#536985';ctx.lineWidth=12;for(const w of WALLS){ctx.beginPath();ctx.moveTo(w.x1,w.y1);ctx.lineTo(w.x2,w.y2);ctx.stroke()}ctx.fillStyle='#ffd23f22';ctx.strokeStyle='#ffd23f';ctx.lineWidth=4;ctx.fillRect(385,1095,130,100);ctx.strokeRect(385,1095,130,100);ctx.fillStyle='#ffd23f';ctx.font='900 17px monospace';ctx.textAlign='center';ctx.fillText('★ WINNER',450,1130);ctx.fillStyle='#fb718522';ctx.fillRect(50,1110,250,80);ctx.fillRect(600,1110,250,80);ctx.fillStyle='#fb7185';ctx.font='700 12px monospace';ctx.fillText('RETURN',175,1150);ctx.fillText('RETURN',725,1150)}
function zone(t,x,y,c){ctx.fillStyle=c;ctx.font='700 13px monospace';ctx.textAlign='left';ctx.fillText(t,x,y)}function drawBall(b){if(b.done&&!b.winner)return;for(let i=0;i<b.trail.length;i++){ctx.globalAlpha=(i/b.trail.length)*.18;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.trail[i][0],b.trail[i][1],b.r*.55,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.angle);ctx.shadowColor=b.winner&&b.done?'#ffd23f':'#0008';ctx.shadowBlur=b.winner&&b.done?25:8;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(0,0,b.r,0,7);ctx.fill();ctx.strokeStyle=b.winner&&b.done?'#fff4a3':'#fff';ctx.lineWidth=3;ctx.stroke();ctx.restore();ctx.fillStyle='#07101d';ctx.strokeStyle='#fff';ctx.lineWidth=2;const label=b.name.length>7?b.name.slice(0,6)+'…':b.name,w=Math.max(50,label.length*13+12);ctx.beginPath();ctx.roundRect(b.x-w/2,b.y+b.r-4,w,24,6);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 11px "Noto Sans KR"';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,b.x,b.y+b.r+8)}
function finish(){S.running=false;document.body.dataset.testComplete='true';document.body.dataset.winners=String(S.won.length);document.body.dataset.collisions=String(S.collisions);$('#statusText').textContent='추첨 완료';$('#phaseText').textContent='WINNER 슬롯 확정';$('#stageNumber').textContent='COMPLETE';$('#stageTitle').textContent='GAME OVER';$('#pauseBtn').disabled=true;$('#restartBtn').disabled=false;$('#resetBtn').disabled=false;$('#resultPanel').hidden=false;$('#winnerList').innerHTML=S.won.map((b,i)=>`<span><small>${i+1}</small> ${escapeHtml(b.name)}</span>`).join('');if(!TEST)$('#resultPanel').scrollIntoView({behavior:'smooth',block:'nearest'})}function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function runTest(stop){const target=stop*23;while(S.time<target&&S.running)step(FIXED);draw();document.body.dataset.testStage=String(stop);if(stop>=1&&!S.running)finish()}window.addEventListener('error',e=>document.body.dataset.jsError=e.message);updateInput();draw();if(TEST){const n=Number(Q.get('count')||20);namesInput.value=Array.from({length:n},(_,i)=>`참가자 ${String(i+1).padStart(2,'0')}`).join('\n');winnerInput.value=String(Math.min(3,n));updateInput();form.requestSubmit()}
