const $=s=>document.querySelector(s),form=$('#drawForm'),namesInput=$('#names'),winnerInput=$('#winnerCount'),setup=$('#setup'),factory=$('#factory'),canvas=$('#factoryCanvas'),ctx=canvas.getContext('2d');
const TEST_PARAMS=new URLSearchParams(location.search),IS_TEST=TEST_PARAMS.has('autotest'),WORLD={w:1800,h:1000},DURATION=IS_TEST?6000:28000,LANE_Y=[175,335,495,655,815];
let state={running:false,paused:false,sound:true,elapsed:0,last:0,cargo:[],winners:[],finalists:new Set(),announced:new Set(),events:new Set(),raf:0,audio:null,shake:0},duplicateConfirmedFor='';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t);
function parsedNames(){return namesInput.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}
function updateInput(){const list=parsedNames(),counts=new Map();list.forEach(n=>counts.set(n,(counts.get(n)||0)+1));const dupes=[...counts].filter(([,n])=>n>1).map(([n,c])=>`${n} × ${c}`);$('#participantCount').textContent=list.length;$('#duplicateNotice').hidden=!dupes.length;$('#duplicateNotice').textContent=dupes.length?`⚠ 중복 이름이 있어요: ${dupes.join(', ')} (각각 별도 참가자로 추첨됩니다)`:''}
namesInput.addEventListener('input',updateInput);winnerInput.addEventListener('input',()=>$('#error').textContent='');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>winnerInput.value=Math.max(1,(+winnerInput.value||1)+(+b.dataset.step)));
function randomInt(max){if(max<=0)return 0;const limit=0x100000000-(0x100000000%max),a=new Uint32Array(1);let v;do{crypto.getRandomValues(a);v=a[0]}while(v>=limit);return v%max}
function fairShuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function colorFor(i){return['#20c7d4','#ff6b2c','#ffc928','#a78bfa','#34d399','#fb7185','#60a5fa','#f97316','#2dd4bf','#e879f9'][i%10]}
function buildCargo(names,count){const entrants=names.map((name,id)=>({name,id})),shuffled=fairShuffle(entrants),winners=shuffled.slice(0,count),winnerOrder=fairShuffle(winners),winnerIds=new Set(winners.map(w=>w.id)),candidateCount=Math.min(entrants.length,Math.max(count+3,6)),extras=fairShuffle(entrants.filter(e=>!winnerIds.has(e.id))).slice(0,candidateCount-count),finalists=[...winnerOrder,...extras];state.winners=winnerOrder;state.finalists=new Set(finalists.map(e=>e.id));const winnerRank=new Map(winnerOrder.map((e,i)=>[e.id,i])),finalRank=new Map(fairShuffle(extras).map((e,i)=>[e.id,i]));state.cargo=entrants.map((e,i)=>({...e,color:colorFor(i),number:i+1,winner:winnerIds.has(e.id),winnerRank:winnerRank.get(e.id),finalist:state.finalists.has(e.id),loseRank:finalRank.get(e.id),lane:(i+randomInt(5))%5,secondLane:randomInt(3),launch:(i%7)*.006+Math.floor(i/7)*.003,event:randomInt(4),spin:randomInt(628)/100}))}
form.addEventListener('submit',e=>{e.preventDefault();const names=parsedNames(),wc=Number(winnerInput.value),err=$('#error');if(!names.length){err.textContent='참여자를 한 명 이상 입력해 주세요.';return}if(!Number.isInteger(wc)||wc<1){err.textContent='당첨자 수를 1명 이상 입력해 주세요.';return}if(wc>names.length){err.textContent=`당첨자 수는 참가자 ${names.length}명보다 많을 수 없습니다.`;return}const signature=names.join('\n');if(new Set(names).size!==names.length&&duplicateConfirmedFor!==signature){if(!confirm('중복된 이름을 각각 별도 참가자로 포함해 추첨할까요?'))return;duplicateConfirmedFor=signature}err.textContent='';initAudio();buildCargo(names,wc);setup.hidden=true;factory.hidden=false;startRun()});
function initAudio(){if(state.audio)return;try{state.audio=new(window.AudioContext||window.webkitAudioContext)()}catch{state.sound=false;$('#soundBtn').textContent='♬ 사운드 OFF'}}
function tone(freq=440,dur=.08,type='square',gain=.025,delay=0){if(!state.sound||!state.audio)return;const a=state.audio,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,a.currentTime+delay);g.gain.setValueAtTime(gain,a.currentTime+delay);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+dur);o.connect(g);g.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+dur)}
function machineSound(){tone(180,.06,'square',.018);tone(260,.07,'square',.014,.07)}function winSound(){[523,659,784,1047].forEach((f,i)=>tone(f,.18,'sine',.035,i*.09))}
function startRun(){state.running=true;state.paused=false;state.elapsed=0;state.last=performance.now();state.announced.clear();state.events.clear();state.shake=0;$('#liveParticipants').textContent=state.cargo.length;$('#winnerProgress').textContent=`0 / ${state.winners.length}`;$('#resultPanel').hidden=true;$('#restartBtn').disabled=true;$('#resetBtn').disabled=true;$('#pauseBtn').disabled=false;$('#pauseBtn').textContent='Ⅱ 일시정지';cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop)}
$('#pauseBtn').onclick=()=>{if(!state.running)return;state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'▶ 재개':'Ⅱ 일시정지';if(!state.paused){state.last=performance.now();state.raf=requestAnimationFrame(loop)}};$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'♬ 사운드 ON':'♬ 사운드 OFF';$('#soundBtn').setAttribute('aria-pressed',String(state.sound));if(state.sound){initAudio();tone(520,.08,'sine')}};$('#restartBtn').onclick=()=>{buildCargo(state.cargo.map(c=>c.name),state.winners.length);startRun()};$('#resetBtn').onclick=()=>{factory.hidden=true;setup.hidden=false;scrollTo({top:0,behavior:'smooth'})};
const SHOWS=[[0,'STAGE 1','자동 분류','입구 대형 분류기','OVERVIEW'],[.075,'STAGE 1','자동 분류','5개 생산라인으로 분산','SORTER CAM'],[.16,'STAGE 2','라인 배틀','A라인 터보 벨트 가속','TURBO CAM'],[.245,'STAGE 2','라인 배틀','C라인 엘리베이터 탑승','LIFT CAM'],[.33,'STAGE 2','라인 배틀','B라인 회전판 추가 회전','ROTARY CAM'],[.405,'STAGE 2','라인 배틀','D라인 로봇 팔 재배치','ROBOT CAM'],[.49,'STAGE 3','대형 합류','5개 라인 중앙으로 쏟아집니다','MERGE WIDE'],[.585,'STAGE 3','재분산','이동식 분류기 방향 전환','SWITCH CAM'],[.665,'STAGE 4','최종 검사','스캐너 검사 · 우회 게이트 작동','SCANNER CAM'],[.75,'STAGE 4','후보 압축','마지막 후보 그룹을 추적합니다','CHASE CAM'],[.835,'FINAL','행운 분류','최종 게이트 잠금','FINAL CAM'],[.89,'FINAL','행운 분류','3 · 2 · 1… 게이트 선택','SLOW MOTION']];
function eventUpdate(p){SHOWS.forEach((s,i)=>{if(p>=s[0]&&!state.events.has(i)){state.events.add(i);$('#stageNumber').textContent=s[1];$('#stageTitle').textContent=s[2];$('#statusText').textContent=s[2];$('#phaseText').textContent=s[3];$('#cameraName').textContent=s[4];const b=$('#eventBanner');b.querySelector('span').textContent=s[3];b.classList.remove('show');requestAnimationFrame(()=>b.classList.add('show'));setTimeout(()=>b.classList.remove('show'),1800);if(i)machineSound()}})}
const CAMS=[[0,900,500,.67],[.07,380,500,1.05],[.15,900,500,.67],[.20,920,175,1.2],[.27,930,495,1.22],[.35,760,335,1.2],[.42,1170,655,1.16],[.49,900,500,.68],[.58,1290,500,1.04],[.66,1430,500,1.12],[.75,1510,500,1.22],[.83,1620,500,1.18],[.90,1660,500,1.42],[1,1680,350,1.22]];
function cameraAt(p){let i=0;while(i<CAMS.length-2&&p>CAMS[i+1][0])i++;const a=CAMS[i],b=CAMS[i+1],t=smooth(clamp((p-a[0])/(b[0]-a[0]))),mobile=innerWidth<600?1.35:1;return{x:lerp(a[1],b[1],t),y:lerp(a[2],b[2],t),z:lerp(a[3],b[3],t)*mobile}}
function loop(now){if(!state.running||state.paused)return;state.elapsed+=Math.min(50,now-state.last);state.last=now;const p=clamp(state.elapsed/DURATION);eventUpdate(p);draw(p);announce(p);$('#progressBar').style.width=`${p*100}%`;const stop=Number(TEST_PARAMS.get('stop'));if(IS_TEST&&stop&&p>=stop){state.paused=true;document.body.dataset.testStage=String(stop);return}if(p<1)state.raf=requestAnimationFrame(loop);else finish()}
function path(points,t){const n=points.length-1,p=clamp(t)*n,i=Math.min(n-1,Math.floor(p)),f=p-i;return{x:lerp(points[i][0],points[i+1][0],f),y:lerp(points[i][1],points[i+1][1],f)}}function localProgress(c,p){return clamp((p-c.launch)/(1-c.launch))}
function cargoPoint(c,p){const t=localProgress(c,p),y=LANE_Y[c.lane];if(t<.16)return path([[60,500],[230,500],[370,y],[510,y]],t/.16);if(t<.49){let u=(t-.16)/.33;const hold=(c.event===1&&u>.38&&u<.56)?(u-.38)*.82:0;u=clamp(u-hold);if(c.lane===0)return path([[510,y],[760,y],[990,y],[1240,y]],u);if(c.lane===1){if(u<.58){const a=c.spin+u/.58*Math.PI*(c.event===2?4:2);return{x:760+Math.cos(a)*105,y:y+Math.sin(a)*72}}return path([[820,y],[1030,y-25],[1240,y]],(u-.58)/.42)}if(c.lane===2)return path([[510,y],[690,y],[690,y-105],[880,y-105],[880,y],[1060,y],[1240,y]],u);if(c.lane===3)return path([[510,y],[720,y],[820,y+(c.event%2?90:-90)],[1030,y],[1240,y]],u);return path([[510,y],[630,y-55],[750,y+55],[870,y-55],[990,y+55],[1110,y-55],[1240,y]],u)}if(t<.59)return path([[1240,y],[1320,500],[1420,500]],(t-.49)/.10);const y2=[350,500,650][c.secondLane];if(t<.68)return path([[1420,500],[1480,y2],[1540,y2]],(t-.59)/.09);if(t<.80){let u=(t-.68)/.12;if(c.event===3&&u>.36&&u<.62)u-=.18;return path([[1540,y2],[1610,y2],[1660,y2],[1580,500]],u)}if(!c.finalist)return path([[1580,500],[1510,700],[1280,880]],(t-.80)/.20);const candidateIndex=[...state.finalists].indexOf(c.id),queueY=370+candidateIndex*46;if(t<.87)return path([[1580,500],[1640,queueY],[1690,queueY]],(t-.80)/.07);if(!c.winner){const release=.90+(c.loseRank||0)*.012;if(t<release)return{x:1690,y:queueY};return path([[1690,queueY],[1610,650],[1430,820]],(t-release)/(1-release))}const spacing=.075/Math.max(1,state.winners.length-1),release=.90+c.winnerRank*spacing;if(t<release)return{x:1690,y:queueY};return path([[1690,queueY],[1740,queueY],[1740,270],[1650,170]],(t-release)/(1-release))}
function draw(p){const cam=cameraAt(p),base=Math.min(canvas.width/WORLD.w,canvas.height/WORLD.h),shake=state.shake>0?(Math.random()-.5)*state.shake:0;state.shake*=.87;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#142031';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2+shake,canvas.height/2+shake);ctx.scale(base*cam.z,base*cam.z);ctx.translate(-cam.x,-cam.y);worldGrid();machines(p);state.cargo.map(c=>({c,pos:cargoPoint(c,p)})).filter(o=>Math.abs(o.pos.x-cam.x)<950/cam.z&&Math.abs(o.pos.y-cam.y)<600/cam.z).sort((a,b)=>a.pos.y-b.pos.y).forEach(o=>drawCargo(o.c,o.pos,cam.z,p));ctx.restore();if(p>.86)drawVignette(p)}
function worldGrid(){ctx.strokeStyle='#223149';ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h);ctx.stroke()}for(let y=0;y<WORLD.h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke()}}
function belt(points,width=74,color='#2b3b51'){ctx.strokeStyle='#101927';ctx.lineWidth=width+9;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.setLineDash([8,26]);ctx.lineDashOffset=-(state.elapsed/18);ctx.strokeStyle='#607087';ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([])}function machineLabel(text,x,y,color='#9eb0c5'){ctx.fillStyle=color;ctx.font='700 16px monospace';ctx.fillText(text,x,y)}
function machines(p){belt([[40,500],[230,500]],88);for(let i=0;i<5;i++){const y=LANE_Y[i];belt([[230,500],[370,y],[1240,y]],70,i===0?'#304b61':'#2b3b51');belt([[1240,y],[1320,500]],65)}belt([[1320,500],[1420,500]],105);[350,500,650].forEach(y=>belt([[1420,500],[1480,y],[1660,y],[1580,500]],58));belt([[1580,500],[1690,370]],65);belt([[1580,500],[1510,700],[1280,880]],65,'#422e3d');belt([[1690,370],[1740,370],[1740,270],[1650,170]],72,'#5a4b20');machineLabel('01  AUTO SORTER',170,70,'#18c6d3');machineLabel('A  TURBO BELT',560,130,'#5ee7f0');machineLabel('B  ROTARY LOOP',650,290,'#ffc928');machineLabel('C  LIFT EXPRESS',620,450,'#a78bfa');machineLabel('D  ROBOT TRANSFER',650,610,'#ff6b2c');machineLabel('E  ZIGZAG LINE',620,770,'#34d399');machineLabel('03  MEGA MERGE',1280,420);machineLabel('04  LASER INSPECTION',1450,270,'#fb7185');machineLabel('★  WINNER DOCK',1580,110,'#ffc928');ctx.save();ctx.translate(270,500);ctx.rotate(Math.sin(state.elapsed/380)*.55);ctx.fillStyle='#18c6d3';ctx.fillRect(-14,-140,28,280);ctx.restore();ctx.save();ctx.translate(760,335);ctx.rotate(state.elapsed/520);ctx.fillStyle='#32465d';ctx.strokeStyle='#ffc928';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,112,0,7);ctx.fill();ctx.stroke();for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.fillStyle='#ffc928';ctx.fillRect(20,-5,72,10)}ctx.restore();const lift=(Math.sin(state.elapsed/650)+1)/2;ctx.strokeStyle='#a78bfa';ctx.lineWidth=8;ctx.strokeRect(650,390,100,190);ctx.fillStyle='#a78bfa55';ctx.fillRect(660,535-lift*120,80,55);const arm=Math.sin(state.elapsed/310)*.62;ctx.save();ctx.translate(900,655);ctx.rotate(arm);ctx.strokeStyle='#ff6b2c';ctx.lineWidth=24;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(135,0);ctx.stroke();ctx.fillStyle='#ffc928';ctx.beginPath();ctx.arc(0,0,30,0,7);ctx.fill();ctx.fillStyle='#ff6b2c';ctx.fillRect(120,-28,20,56);ctx.restore();ctx.strokeStyle='#fb7185';ctx.lineWidth=5;for(let x=1510;x<1640;x+=22){ctx.globalAlpha=.35+.45*Math.sin(state.elapsed/130+x);ctx.beginPath();ctx.moveTo(x,310);ctx.lineTo(x,690);ctx.stroke()}ctx.globalAlpha=1;const gateOpen=p>.90;ctx.strokeStyle=gateOpen?'#34d399':'#fb7185';ctx.lineWidth=17;ctx.beginPath();ctx.moveTo(1705,300);ctx.lineTo(1705,gateOpen?210:510);ctx.stroke();ctx.fillStyle=gateOpen?'#34d399':'#fb7185';ctx.beginPath();ctx.arc(1705,190,13,0,7);ctx.fill();for(let i=0;i<3;i++){ctx.fillStyle=(p>.84&&Math.floor(state.elapsed/230+i)%2)?'#ff3b49':'#4b2330';ctx.beginPath();ctx.arc(1600+i*34,250,10,0,7);ctx.fill()}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function drawCargo(c,pos,zoom,p){ctx.save();ctx.translate(pos.x,pos.y);ctx.scale(zoom>1.1?1.08:1,zoom>1.1?1.08:1);if(c.winner&&p>.9){ctx.shadowColor='#ffc928';ctx.shadowBlur=28}ctx.fillStyle=c.color;roundRect(-46,-27,92,54,8);ctx.fill();ctx.strokeStyle=c.finalist&&p>.77?'#fff':'#0b1320';ctx.lineWidth=c.finalist&&p>.77?5:3;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#0b1320';ctx.beginPath();ctx.arc(-34,-20,13,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 11px monospace';ctx.fillText(String(c.number).padStart(2,'0'),-34,-20);ctx.fillStyle='#fff';roundRect(-37,-12,76,29,4);ctx.fill();ctx.fillStyle='#111827';ctx.font=`800 ${c.name.length>7?10:13}px "Noto Sans KR"`;ctx.fillText(c.name.length>10?c.name.slice(0,9)+'…':c.name,1,3);ctx.restore()}
function drawVignette(p){const g=ctx.createRadialGradient(canvas.width/2,canvas.height/2,canvas.height*.12,canvas.width/2,canvas.height/2,canvas.width*.65);g.addColorStop(0,'transparent');g.addColorStop(1,`rgba(0,0,0,${.15+clamp((p-.9)/.1)*.35})`);ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}
function announce(p){state.winners.forEach((w,i)=>{const threshold=.915+i*(.075/Math.max(1,state.winners.length-1));if(p>=threshold&&!state.announced.has(i)){state.announced.add(i);state.shake=12;$('#winnerProgress').textContent=`${i+1} / ${state.winners.length}`;const toast=$('#winnerToast');toast.textContent=`★ ${i+1}번째 당첨 화물 · ${w.name}`;toast.classList.remove('show');requestAnimationFrame(()=>toast.classList.add('show'));setTimeout(()=>toast.classList.remove('show'),Math.min(2100,10500/state.winners.length));winSound();confetti()}})}
function confetti(){for(let i=0;i<34;i++){const s=document.createElement('i');Object.assign(s.style,{position:'absolute',zIndex:9,left:`${45+Math.random()*10}%`,top:'18%',width:'6px',height:'11px',background:colorFor(i),pointerEvents:'none',transition:'transform 1.5s ease-in, opacity 1.5s'});$('.canvas-wrap').append(s);requestAnimationFrame(()=>{s.style.transform=`translate(${(Math.random()-.5)*620}px,${180+Math.random()*330}px) rotate(${Math.random()*720}deg)`;s.style.opacity='0'});setTimeout(()=>s.remove(),1600)}}
function finish(){state.running=false;document.body.dataset.testComplete='true';$('#statusText').textContent='추첨 완료';$('#phaseText').textContent='모든 당첨 화물 배송 완료';$('#stageNumber').textContent='COMPLETE';$('#stageTitle').textContent='배송 완료';$('#pauseBtn').disabled=true;$('#restartBtn').disabled=false;$('#resetBtn').disabled=false;$('#resultPanel').hidden=false;$('#winnerList').innerHTML=state.winners.map((w,i)=>`<span><small>${i+1}</small> ${escapeHtml(w.name)}</span>`).join('');$('#resultPanel').scrollIntoView({behavior:'smooth',block:'nearest'})}function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}window.addEventListener('error',e=>document.body.dataset.jsError=e.message);updateInput();draw(0);if(IS_TEST){namesInput.value=Array.from({length:20},(_,i)=>`참가자 ${String(i+1).padStart(2,'0')}`).join('\n');winnerInput.value='3';updateInput();form.requestSubmit();const testFrame=Number(TEST_PARAMS.get('stop')||1);state.paused=true;state.elapsed=testFrame*DURATION;eventUpdate(testFrame);draw(testFrame);announce(testFrame);$('#progressBar').style.width=`${testFrame*100}%`;document.body.dataset.testStage=String(testFrame);if(testFrame>=1)finish()}
